# These are supported funding model platforms

custom: ["https://etherscan.io/address/0xf79931DBb16C88D81Ef21BF7B89b1a96A8e62E3D"]
custom: ETH/USDT/USDC ERC=20 0xf79931DBb16C88D81Ef21BF7B89b1a96A8e62E3D
